name: sportal
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  easy_mask: ^2.0.1
  ensure_visible_when_focused: ^1.1.1
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  flutter_screenutil: ^5.4.0+1
  flutter_secure_storage: ^6.1.0
  fluttertoast: ^8.0.8
  get: ^4.6.5
  google_ml_kit: ^0.7.0
  http: ^0.13.5
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.1
  lottie: ^2.0.0
  open_filex: ^4.3.1
  pdf: ^3.8.4
  permission_handler: ^8.1.4+2
  pretty_qr_code_plus: ^0.0.1
  provider: ^6.0.4
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  twilio_flutter: ^0.0.9
  widgets_to_image: ^0.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
